MsPos/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MsPos.Data;
using MsPos.Models;

namespace MsPos.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly MsPosDbcontext _context;

        public InvoicesController(MsPosDbcontext context)
        {
            _context = context;
        }
     

        // GET: Invoices
        public async Task<IActionResult> Index()
        {
              return _context.Invoice != null ? 
                          View(await _context.Invoice.ToListAsync()) :
                          Problem("Entity set 'MsPosDbcontext.Invoice'  is null.");
        }

        // GET: Invoices/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Invoice == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.InvoiceId == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: Invoices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InvoiceId,InvoiceNumber,CustomerId,CustomerName,SalePrice,PurchasePrice,CreatedDate,TotalAmount,Discount,PaymentMethod,Status")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invoice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Invoice == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice.FindAsync(id);
            if (invoice == null)
            {
                return NotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("InvoiceId,InvoiceNumber,CustomerId,CustomerName,SalePrice,PurchasePrice,CreatedDate,TotalAmount,Discount,PaymentMethod,Status")] Invoice invoice)
        {
            if (id != invoice.InvoiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.InvoiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Invoice == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.InvoiceId == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Invoice == null)
            {
                return Problem("Entity set 'MsPosDbcontext.Invoice'  is null.");
            }
            var invoice = await _context.Invoice.FindAsync(id);
            if (invoice != null)
            {
                _context.Invoice.Remove(invoice);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceExists(long id)
        {
          return (_context.Invoice?.Any(e => e.InvoiceId == id)).GetValueOrDefault();
        }
    }
}

MsPos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MsPos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/css/bootswatchtheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MsPos.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MsPos</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
          
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="PurchaseStock" asp-action="Index">PurchaseStock</a>
        </li>
       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Daily Sale Report</a>
            <a class="dropdown-item" href="#">Daily Purchase Report</a>
            <a class="dropdown-item" href="#">Daily Profit Report</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li> <li class="nav-item">
          <a class="nav-link"asp-area="" asp-controller="Management" asp-action="Index">Management</a>
        </li>
      </ul>
    @*  <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
                    @*@if (!(Model.Username ==null)) { 
                    *@    
            <form method = "post" asp-controller = "Account" asp-action = "Logout"> 
               <input type = "submit" value = "Logout"/> 
            </form> 
      @*   } else {  
            <a asp-controller = "Home" asp-action = "Login">Login</a> 
         }  *@
    </div>
  </div>
</nav>
      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MsPos - 
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/plugins/jquery-ui/jquery-ui.js "></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MsPos/Views/Shared/_Notification.cshtml
@if(TempData["success"] !=null){
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   
    <script type="text/javascript">
toastr.success('@TempData["success"]');
    </script>
   

}
@if(TempData["error"] !=null){ 
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   
   <script type="text/javascript">
toastr.error('@TempData["error"]');
    </script>
    
}
@if(TempData["warn"] !=null){ 
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   
   <script type="text/javascript">
toastr.warning('@TempData["warn"]');
    </script>
    
}